### ISSUE TITLE
Checking in on the status of this crate

### ISSUE THREAD

**Issue by ddimaria** [webrtc-rs/dtls#3]
Thanks for making the effort to port Pion over to Rust 🙏 , it is a massive undertaking.  I've been playing around with this crate and ran into an issue with the handshake (can't get past flight 1 as a client), and wanted to rule out any library issues.  Have you been able to get this crate working with a handshake from a browser?  If so, was it as a client, server, or both (also, which browser)? Would you mind sharing any code you have that you use to validate features (or links to repos that use this crate)? It would be greatly appreciated.  Thank you!

**Comment by rainliu** [comment]
@ddimaria, thanks for interesting in usage of dtls crate. I have to admit that the dtls crate is still immature. I haven't tried the tests between it and a browser yet. I am supposed to postpone those dtls e2e tests until webrtc crate is finished, since dtls will be extensively used in webrtc crate, which will have e2e test between webrtc crate and browsers.

Have you tried Pion's dtls e2e tests between Pion dtls and browser? I always want to set up interop tests between Pion and WebRTC-rs first, but lack of bandwidth to do those interop tests. The help from the community is greatly appreciated.
